### ISSUE TITLE
Implemention of the Grid Sequencer

### ISSUE THREAD

**Issue by Xon77** [v7b1/mi-UGens#13]
Hello,

Just a question :
Is there a plan to implement the topographic sequencer Grids in SuperCollider,
either as a Ugen or pattern ?

I think it could be great!

**Comment by v7b1** [comment]
Hi Christophe - it's on my list :) can't promise anything, though. 
it looks simple enough, but it's based on avr rather than stm (like the other modules). This doesn't make the translation any easier...

**Comment by capital-G** [comment]
I started working on a port to using the sc pattern system instead of a ugen

https://github.com/capital-G/sc-grids

**Comment by v7b1** [comment]
@capital-G looks nice! thanks for posting.
a ugen version is also on its way.
