### ISSUE TITLE
MiGrids fails to build due to incorrect AVRLIB_PATH

### ISSUE THREAD

**Issue by catniptwinz** [v7b1/mi-UGens#17]
Building on Arch Linux (kernel 6.3.1-arch1-1) fails with:

```
CMake Error at CMakeLists.txt:40 (add_library):
  Cannot find source file:

    /home/[REDACTED]/packages/custom-vcs/supercollider-mi-ugens-git/src/eurorack/avrlib/base.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:40 (add_library):
  No SOURCES given to target: MiGrids


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

It seems that this is due to the change to line 7 of CMakeLists.txt in [783e8d8](https://github.com/v7b1/mi-UGens/commit/78e83d8a6454eac0523a7103f3e97900cee913da). Reverting from:

`set(MUTABLE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/../../eurorack")`

to:

`set(MUTABLE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/../eurorack")`

Appears to resolve the issue.

**Comment by v7b1** [comment]
Fixed! Thanks for finding and reporting this. It was a left over of my efforts to create a completely cmake based build system. If you have a minute, feel free to check out the 'new_cmake_build-system' branch and report back how it works on Linux.

**Comment by catniptwinz** [comment]
Thanks likewise! Tested and confirmed that the most recent commit is building as expected.

The 'new_cmake_build-system' branch appears to be working as well:

```
$ git clone --branch new_cmake_build-system --recurse-submodules https://github.com/v7b1/mi-UGens
$ mkdir build && cd build
$ cmake -DSC_PATH="[PATH TO SC SOURCE]" -DCMAKE_BUILD_TYPE="Release" ..
$ make
```
