### ISSUE TITLE
MSVC compatibility

### ISSUE THREAD

**Issue by brianlheim** [v7b1/mi-UGens#6]
I noticed these UGens do not compile under Windows MSVC 2019. Would you have any interest in accepting a PR to add support for that compiler? I played with it a bit last night and got a few of the components in this repo compiling without too many changes.

**Comment by v7b1** [comment]
Yes, sure. I can't test/verify the necessary changes for windows, though.

**Comment by brianlheim** [comment]
OK!

I could look into adding a github actions workflow too if you're open to it.
