### ISSUE TITLE
Plugin packaging

### ISSUE THREAD

**Issue by ndr-brt** [v7b1/mi-UGens#8]
Since it's not possible to distribute plugins through quarks (as was discussed in #4), maybe a solution could be to release the binary package for every OS (linux/win/macosx). I just read an inspiring article about how to use github actions to do that:

https://madskjeldgaard.dk/posts/how-to-gh-action/

**Comment by v7b1** [comment]
Thanks, I'll check it out, was soon as I find the time.

**Comment by v7b1** [comment]
thanks, @ndr-brt - worked out nicely!
